### ISSUE TITLE
Esplicitare che un branch rc-inhibit bisogna settare l'upstream prima di finire

### ISSUE THREAD

**Issue by ricByte** [Byte-Code/git-trunk-flow#3]
Lanciando `git create-rc-inhibit` e successivamente `git finish-rc-inhibit` se il branch non é mai stato pushato dovrebbe pushare con l'opzione `-u`

_Log d'esempio_
```
fatal: The current branch 'bugfix/30240#1' has no upstream branch.

To push the current branch and set the remote as upstream

  (use "git push --set-upstream origin bugfix/30240#1)

When ready, re-run this command
```

**Comment by neatshell** [comment]
It's by design. Sebbene lo script non faccia il push sottobanco, ti mostra il comando da lanciare per poterlo pushare, ovvero: `git push --set-upstream origin bugfix/30240#1` questo e' voluto per darti la possibilita' magari di aggiungere il flag `--no-verify` se vuoi lanciare l'hook di pre-push manualmente.
